### ISSUE TITLE
门店获取类目接口错误

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#10]
配置文件中key为url.poi.categories.get的接口地址为http://api.weixin.qq.com/cgi-bin/api_getwxcategory
。
官方的接口为	
http://api.weixin.qq.com/cgi-bin/poi/getwxcategory?access_token=TOKEN

**Comment by borball** [comment]
Fixed and snapshot released at https://github.com/borball/weixin-sdk/commit/0b878611461d796024d95d71d172aaf747325a29
