### ISSUE TITLE
缺少获取自定义菜单配置接口

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#12]
详情：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1434698695&token=&lang=zh_CN

**Comment by borball** [comment]
fixed at https://github.com/borball/weixin-sdk/commit/79a36fff4b2b111e9c7cfbd48b14fc68d1bec6ac

**Comment by borball** [comment]
more fixed: https://github.com/borball/weixin-sdk/commit/ce6d7d179fadb0666d7196b7429878bfca682236
