### ISSUE TITLE
Users batchGet方法传String...不方便

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#13]
用UserPagination 的getUsers方法拿出的是List<String>类型的数据，传进Users.batchGet方法内还要再转一次

**Comment by wodenwang** [comment]
这个是跟官方API一样的.官方的API也是要求分两步去获取数据.

**Comment by CodinngLee** [comment]
我是指参数类型直接就是List了，不用再手动转List成String...

**Comment by borball** [comment]
已经有个方法 public List<User> batchGet(List<Map<String, String>> openIds) ， 再用List<String>就冲突了，又不太想改方法名，List和数组也就一步转化，set it as won't fix。
