### ISSUE TITLE
关于XmlObjectMapper.toXml(Ojbect o)返回带有xmlns问题

### ISSUE THREAD

**Issue by chenkaifan** [borball/weixin-sdk#14]
你好，为什么我用了TextMessage生成返回给微信的时候，你的接口XmlObjectMapper.toXml(Ojbect o)的时候，他返回《xml xmlns=""》《/xml》，而微信则不需要xmlns这个namespace。我查看了XmlObjectMapper则没有不要默认命名空间的接口。谢谢

**Comment by borball** [comment]
企业号？如果你想返回XML格式给微信（同步消息），你应该使用TextXmlMessage而不是TextMessage（使用JSON，异步消息）

**Comment by borball** [comment]
另外企业号有QyXmlMessages和Messages应该够用，基本上不需要直接使用XmlObjectMaper之类。

**Comment by chenkaifan** [comment]
hi,刚手误，我是调用TextXmlMessage进行同步消息回复的。但是一直错误的，我跟踪，发送的消息为
《xml xmlns=""》<MsgType><![CDATA[text]]></MsgType><ToUserName><![CDATA[xxxx]]></ToUserName><FromUserName><![CDATA[xxxxx]]></FromUserName><CreateTime>146475991</CreateTime><Content><![CDATA[你好啊2]]></Content>《/xml》

**Comment by chenkaifan** [comment]
如下：
// 关注
TextXmlMessage text = new TextXmlMessage();

text.setContent("您好啊2");
text.setToUser(clickEvent.getFromUser());
text.setFromUser(clickEvent.getToUser());
String xml =MpXmlMessages.toXml(text);
System.out.println(xml);

**Comment by chenkaifan** [comment]
如果是《xml》<![CDATA[text]]><![CDATA[xxxx]]><![CDATA[xxxxx]]>146475991<![CDATA[你好啊2]]>《/xml》是正确的，既不要xmlns这个

**Comment by borball** [comment]
你跑一下case：MpXmlMessagesTest.testTextToXML， 我这里是返回：`<xml><MsgType><![CDATA[text]]></MsgType><ToUserName><![CDATA[to user]]></ToUserName><FromUserName><![CDATA[from user]]></FromUserName><CreateTime>146478867</CreateTime><Content><![CDATA[content]]></Content></xml>`

**Comment by borball** [comment]
你没有加woodstox-core到你的classpath?
            <dependency>
                <groupId>com.fasterxml.woodstox</groupId>
                <artifactId>woodstox-core</artifactId>
                <version>${woodstox-core.version}</version>
            </dependency>
