### ISSUE TITLE
demo中微信公众号处理微信服务器响应消息问题

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#16]
公众号返回“该公众号暂时无法提供服务请稍后再试”的消息，该如何处理？

**Comment by wodenwang** [comment]
这种情况是因为微信平台主动发送消息到你的服务器,却没有得到合法反馈.所以微信平台认为你服务器已断开.

可以检查一下在公众平台配置的回调信息是否有误.合法的网址格式如下:
http://{domain}/wx/mp/{appid}

**Comment by CodinngLee** [comment]
平台配置已配好，已通过校验。写的例子是以你们的DEMO项目为主，return了""字符串。但是还是返回这种提示

**Comment by wodenwang** [comment]
不清楚你用的是哪个case.或者你可以把case和报错信息帖出来.

**Comment by CodinngLee** [comment]
就是weixin-sdk demo项目下 WxCallbackController 类
/**
     * 公众号回调接口
     * 这里为了演示方便使用单个固定URL，实际使用的时候一个一个系统可能有多个公众号，这样的话需要有个分发逻辑：
     * 比如callback url可以定义为  /wx/mp/[公众号的appId]，通过appId构造不同的AppSetting
     *
     * @param signature
     * @param msg_signature
     * @param timestamp
     * @param nonce
     * @param echostr
     * @param encrypt_type
     * @param content
     * @return
     */
    @RequestMapping("/wx/mp")
    @ResponseBody
    public String mp(@RequestParam(value="signature") String signature,
                     @RequestParam(value="msg_signature", required = false) String msg_signature,
                     @RequestParam(value="timestamp") String timestamp,
                     @RequestParam(value="nonce") String nonce,
                     @RequestParam(value="echostr", required = false) String echostr,
                     @RequestParam(value="encrypt_type", required = false) String encrypt_type,
                     @RequestBody(required = false) String content) {

        logger.info("signature={}, msg_signature={}, timestamp={}, nonce={}, echostr={}, encrypt_type={}", signature, msg_signature, timestamp, nonce, echostr, encrypt_type);

        AppSetting appSetting = AppSetting.defaultSettings();
        try {
            if(!SHA1.getSHA1(appSetting.getToken(), timestamp, nonce).equals(signature)) {
                logger.warn("非法请求.");
                return "非法请求.";
            }
        } catch (AesException e) {
            logger.error("check signature failed:", e);
            return "非法请求.";
        }

        if (!StringUtils.isEmpty(echostr)) {
            return echostr;
        }

        XmlMessageHeader xmlRequest = null;
        if("aes".equals(encrypt_type)) {
            try {
                MessageDecryption messageDecryption = new MessageDecryption(appSetting.getToken(), appSetting.getAesKey(), appSetting.getAppId());
                xmlRequest = MpXmlMessages.fromXml(messageDecryption.decrypt(msg_signature, timestamp, nonce, content));
                XmlMessageHeader xmlResponse = mpDispatch(xmlRequest);

                if(xmlResponse != null) {
                    try {
                        return messageDecryption.encrypt(XmlObjectMapper.defaultMapper().toXml(xmlResponse), timestamp, nonce);
                    } catch (JsonProcessingException e) {
                    }
                }
            } catch (AesException e) {
            }
        } else {
            xmlRequest = MpXmlMessages.fromXml(content);
            XmlMessageHeader xmlResponse = mpDispatch(xmlRequest);
            if(xmlResponse != null) {
                try {
                    return XmlObjectMapper.defaultMapper().toXml(xmlResponse);
                } catch (JsonProcessingException e) {
                }
            }
        }

        return "";
    }

    private XmlMessageHeader mpDispatch(XmlMessageHeader xmlRequest) {
        if(!duplicatedMessageChecker.isDuplicated(xmlRequest.getFromUser() + xmlRequest.getCreateTime().getTime())) {
            String welcome = "您好:" + Users.defaultUsers().get(xmlRequest.getFromUser()).getNickName();
            CareMessages.defaultCareMessages().text(xmlRequest.getFromUser(), welcome);

            if (xmlRequest instanceof EventRequest) {
                EventRequest eventRequest = (EventRequest) xmlRequest;
                logger.debug("事件请求[{}]", eventRequest.getEventType().name());
                CareMessages.defaultCareMessages().text(xmlRequest.getFromUser(), "事件请求:" + eventRequest.getEventType().name());
            } else {
                logger.debug("消息请求[{}]", xmlRequest.getMsgType().name());
                CareMessages.defaultCareMessages().text(xmlRequest.getFromUser(), "消息请求:" + xmlRequest.getMsgType().name());
            }
        } else {
            logger.warn("Duplicated message: {} @ {}", xmlRequest.getMsgType(), xmlRequest.getFromUser());
        }

        //需要同步返回消息（被动回复）给用户则构造一个XmlMessageHeader类型，比较鸡肋，因为处理逻辑如果比较复杂响应太慢会影响用户感知，建议直接返回null；
        //要发送消息给用户可以参考上面的例子使用客服消息接口进行异步发送
        return null;
    }

**Comment by borball** [comment]
@CodinngLee 能debug一下看看代码哪行出的问题吗?

**Comment by CodinngLee** [comment]
就是没发现什么问题……

**Comment by borball** [comment]
代码走到
CareMessages.defaultCareMessages().text(xmlRequest.getFromUser(), "事件请求:" + eventRequest.getEventType().name());
或者：
CareMessages.defaultCareMessages().text(xmlRequest.getFromUser(), "消息请求:" + xmlRequest.getMsgType().name());
了？

**Comment by CodinngLee** [comment]
这段代码屏蔽掉，也是直接弹出两条“该公众号暂时无法提供服务请稍后再试”

**Comment by borball** [comment]
那就是代码没进来，你直接断点到 AppSetting appSetting = AppSetting.defaultSettings(); 看看到哪一步出错了？

**Comment by CodinngLee** [comment]
你们试了下weixin-sdk demo项目的代码，会出现这种提示吗？

**Comment by CodinngLee** [comment]
将mpDispatch方法里的代码全注释，全留return null; 关注事件时进入的公众号不会显示“该公众号暂时无法提供服务请稍后再试”，通过扫码事件扫进来时会显示。是不是扫码还要做什么特殊处理？？

**Comment by borball** [comment]
@CodinngLee 你更新下：https://github.com/borball/weixin-sdk-demo/commit/76053800f55f915d1dd6dd5c48facdb29d66aace
