### ISSUE TITLE
使用XmlMessageHeader转换格式不正确

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#17]
XmlMessageHeader xmlResponse
用XmlObjectMapper.defaultMapper().toXml(xmlResponse)转为微信消息回复的格式时，输出结果为
```
<XmlMessageHeader>
<MsgType></MsgType>
<ToUserName></ToUserName>
<FromUserName></FromUserName>
<CreateTime></CreateTime>
</XmlMessageHeader>

```
微信要求的格式为
```
<xml>
<MsgType></MsgType>
<ToUserName></ToUserName>
<FromUserName></FromUserName>
<CreateTime></CreateTime>
</xml>

```

**Comment by borball** [comment]
请使用XmlMessageHeader的各个子类而不是直接使用XmlMessageHeader。
另外尽量避免直接使用使用XmlObjectMapper.defaultMapper(); 你可以使用MpXmlMessages.fromXml 或者MpXmlMessages.toXml()

**Comment by borball** [comment]
@CodinngLee 你更新下：https://github.com/borball/weixin-sdk-demo/commit/76053800f55f915d1dd6dd5c48facdb29d66aace
