### ISSUE TITLE
weixin-sdk 什么时候可以支持集群。accesstoken可以持久化？或者有没有预留这个接口出来提供给开发者

### ISSUE THREAD

**Issue by yyhSuper** [borball/weixin-sdk#19]

**Comment by borball** [comment]
@yyhSuper 有计划做支持（预留接口），暂时没排上版本。see https://github.com/borball/weixin-sdk/issues/1

**Comment by leopeng1995** [comment]
@borball 可以不可以像Nodejs版本的[wechat-oauth](https://github.com/node-webot/wechat-oauth/blob/master/lib/oauth.js#L61)一样，由用户实现保存token和获取token的回调函数呢？

**Comment by borball** [comment]
Fixed with https://github.com/borball/weixin-sdk/commit/c9e08c1d9fbe24bb503c22d2798b7159d809f245 ;
扩展方式：
1：继承AccessTokenHolder，实现自己的token保存机制，比如存到数据库、共享磁盘或者分布式缓存。
2：修改wx-<xyz>-settings.xml文件，增加element: tokenHolderClass，值为步骤一中扩展类的全路径。

@yyhSuper @leopeng1995 没充分测试，有问题可以跟楼，Thanks!

**Comment by howareyouo** [comment]
@borball `AccessTokenHolder` 里没有默认的无参构造函数, 导致`MpWxClientFactory`里调用`newInstance`实例化时候报错, 另外 `HttpClient`也是在父类的构造函数里初始化的, 子类没办法初始化, 因为`httpClient`是私有的....
![image](https://user-images.githubusercontent.com/1881595/59404237-6ba5ef80-8dd8-11e9-9516-68d6f917a291.png)
