### ISSUE TITLE
获取新闻列表数据时，微信url没有在MpArticle模型里

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#2]

**Comment by borball** [comment]
查了下文档URL2016年一月份新增加的，代码没跟着更新，我尽快加进去。

**Comment by borball** [comment]
Fixed in https://github.com/borball/weixin-sdk/commit/292f6c43408de2b1686db7a73e8e21093c04c824, feel free to close it. @CodinngLee
