### ISSUE TITLE
微信公众号支付接口是不需要证书的

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#20]
微信公众号支付接口是不需要证书的，但你这的PaySetting怎么还要填证书的路径，这个应该和退款的分开吧 @borball

**Comment by borball** [comment]
你说的是公众号里面支付相关的JS-SDK吧，除了JS-SDK公众号支付还有其他功能需要用到证书，暂时没有计划剥离JS-SDK出去。

**Comment by CodinngLee** [comment]
是的，刚好我这有个临时项目是用JS-SDK公众号支付，但不涉及到退款，仅仅是支付，对方没有给我们证书。

**Comment by borball** [comment]
可以填个假的进去应该不会影响JS API的使用。

**Comment by vip365** [comment]
好的，多谢，后续工作试试。
