### ISSUE TITLE
微信创建卡券：begin_timestamp和end_timestamp 字段在json格式化的时候应该是十位的时间戳

### ISSUE THREAD

**Issue by yyhSuper** [borball/weixin-sdk#21]
微信给的例子,正确的格式：
date_info: {
                    "type": "DATE_TYPE_FIX_TIME_RANGE", 
                    "begin_timestamp": 1397577600, 
                    "end_timestamp": 1472724261
                }
weixin-sdk格式化的格式：
 "date_info":{  
               "type":"DATE_TYPE_FIX_TIME_RANGE",
               "begin_timestamp":"2016-08-23 00:00:00",
               "end_timestamp":"2016-08-30 00:00:00",
               "fixed_term":0,
               "fixed_begin_term":0
            }

**Comment by borball** [comment]
fixed at https://github.com/borball/weixin-sdk/commit/ba19f9b23e9df52a6a25df499b07eb01f3dee48d
