### ISSUE TITLE
判断条件写反了。

### ISSUE THREAD

**Issue by yyhSuper** [borball/weixin-sdk#24]
![image](https://cloud.githubusercontent.com/assets/9104878/21335643/3291f22c-c69b-11e6-8b74-56092bf05870.png)

**Comment by WhisperG** [comment]
对的呀

**Comment by WhisperG** [comment]
|| -> &&

**Comment by WhisperG** [comment]
if(clazz != null && !"".equals(clazz))

**Comment by borball** [comment]
fixed with https://github.com/borball/weixin-sdk/commit/b5d2aaf67fa06840951e47cf1d090b44772249ae

**Comment by borball** [comment]
@yyhSuper @WhisperG
