### ISSUE TITLE
WxClient.java里，refreshToken方法执行时，线程安全吗？

### ISSUE THREAD

**Issue by tsingmuhe** [borball/weixin-sdk#27]

**Comment by borball** [comment]
1、如果使用封装好的API，WxClient 是单例，实际使用过程不需要直接使用WxClient。
2、里面的token保存是否线程安全是由AccessTokenHolder的实现决定的，默认的com.riversoft.weixin.common.DefaultAccessTokenHolder 里面是线程安全的，在一次重构的时候synchronized关键字被漏掉了。https://github.com/borball/weixin-sdk/commit/54b1f21be1fe69ef8790d8c9609765072a6c335f 
3、如果要扩展’AccessTokenHolder (比如需要多实例部署)，实现者要自己保证该实现线程安全。
