### ISSUE TITLE
微信MD5签名问题

### ISSUE THREAD

**Issue by yyhSuper** [borball/weixin-sdk#28]
MD5摘要加密签名需要设置UTF-8编码格式，否则报签名错误

![image](https://cloud.githubusercontent.com/assets/9104878/21536402/903e3c36-cdbd-11e6-91b6-3a376a95224d.png)

**Comment by borball** [comment]
哪里的代码？不像是我的风格？：）

**Comment by yyhSuper** [comment]
weixin-common 工程下面的

com/riversoft/weixin/common/util/MD5.java

**Comment by borball** [comment]
我写了测试用例貌似和commons-codec没区别，不知道你什么场景下触发这个问题的。
anyway 我用DigestUtils.md5Hex(origin) 替换了实现。

**Comment by yyhSuper** [comment]
我是在调用微信统一下单接口的时候，SDK里面不是封装了签名的方法嘛。在没有改成UTF-8之前微信是一直报签名错误。改成UTF-8之后这个错误就没有了。

**Comment by borball** [comment]
忽略上面的comment，提交代码的时候issue id填错了。
