### ISSUE TITLE
执行Materials.updateMpNews发生NullPointerException异常

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#3]
java.lang.NullPointerException
	at com.riversoft.weixin.common.WxClient.appendAccessToken(WxClient.java:405)
	at com.riversoft.weixin.common.WxClient.post(WxClient.java:292)
	at com.riversoft.weixin.mp.media.Materials.updateMpNews(Materials.java:123)

String url = WxEndpoint.get("url.material.mpnews.update");
发现url.material.mpnews.update此key，不存在于wx-mp-endpoint.properties配置文件中
url.material.mpnews.update应对应接口地址为：https://api.weixin.qq.com/cgi-bin/material/update_news?access_token=ACCESS_TOKEN

**Comment by borball** [comment]
Fixed in https://github.com/borball/weixin-sdk/commit/65a091ac6b64c7489833022ad851af4c7dffd8ee. @CodinngLee

**Comment by CodinngLee** [comment]
麻烦修改后的做份snapshots到oss-snapshots

**Comment by borball** [comment]
snapshot is deployed in oss。
