### ISSUE TITLE
日期转换错误DateDeserializer

### ISSUE THREAD

**Issue by wangchaowu** [borball/weixin-sdk#30]
public class DateDeserializer extends JsonDeserializer<Date> {

    @Override
    public Date deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws IOException {
        //操蛋的微信，为啥不是毫秒
        long time = Long.valueOf(jsonParser.getText()) * 1000;
        return new Date(time);
    }
}
-----------------------------------
微信时间格式是：20141030133525
上面乘1000这么转换为Date不对吧

**Comment by borball** [comment]
哪个API？有报文例子吗？

**Comment by wangchaowu** [comment]
微信订单查询接口接口：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_2
time_end字段
你可以看测试方法：com.riversoft.weixin.pay.mp.OrdersTest.testQueryOrder
你打印下date看下:
OrderQueryResponse response = Orders.defaultOrders().query(orderQueryRequest);
Date date = response.getTimeEnd();
