### ISSUE TITLE
weixin-sdk 没有添加JS-SDK的模块吗？

### ISSUE THREAD

**Issue by yyhSuper** [borball/weixin-sdk#32]
https://mp.weixin.qq.com/wiki?id=mp1445241432&lang=zh_CN

**Comment by borball** [comment]
JS_SDK唯一需要用到后台封装的只有验证签名这块，已经封装到 JsAPIs.createJsAPISignature；其他的都是前端JavaScritpt 的事情。

**Comment by yyhSuper** [comment]
应该还少了吧，比如微信卡券，拉取适用卡券列表并获取用户选择信息里面的cardSign参数 需要在后端获取api_ticket.

api_ticket 地址：https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=wx_card

**Comment by borball** [comment]
@yyhSuper，没测试过，你试试看。JsAPIs.createWxCardJsAPISignature
