### ISSUE TITLE
企业付款-签名错误

### ISSUE THREAD

**Issue by eejron** [borball/weixin-sdk#33]
收款人做校验时，收款人是中文名；或者付款描述包含中文都会导致签名错误。

但是在Junit直接测试，即使收款人和付款描述包含中文也没有出现“签名错误”问题。

**Comment by borball** [comment]
@eejron 请提供业务代码和JUnit测试代码。

**Comment by eejron** [comment]
应该是我这边问题，乱码是这边项目的问题，干扰到我判断了。
签名错误是金额是float，转换是没去掉小数点导致的。
