### ISSUE TITLE
DefaultAccessTokenHolder

### ISSUE THREAD

**Issue by mycoco2014** [borball/weixin-sdk#37]
MpWxClientFactory:
accessTokenHolder = (AccessTokenHolder)Class.forName(clazz).newInstance(); //默认的没有构造函数，确定可以？？？
accessTokenHolder.setClientId(appSetting.getAppId());
accessTokenHolder.setClientSecret(appSetting.getSecret());
accessTokenHolder.setTokenUrl(url);

DefaultAccessTokenHolder:

public class DefaultAccessTokenHolder extends AccessTokenHolder {

    private AccessToken accessToken;

    public DefaultAccessTokenHolder(String tokenUrl, String clientId, String clientSecret){
        super(tokenUrl, clientId, clientSecret);
    }

    @Override
    public synchronized AccessToken getAccessToken() {
        if (accessToken == null || accessToken.expired()) {
            refreshToken();
        }
        return accessToken;
    }

    @Override
    public synchronized void refreshToken() {
        if (accessToken == null || accessToken.expired()) {
            String content = fetchAccessToken();
            AccessToken accessToken = AccessToken.fromJson(content);
            this.accessToken = accessToken;
        }
    }

    @Override
    public void expireToken() {
        accessToken.setExpiresIn(-30);//强制设置为无效
    }
}

哎。。。。

**Comment by borball** [comment]
`else {
                try {
                    accessTokenHolder = (AccessTokenHolder)Class.forName(clazz).newInstance();
                    accessTokenHolder.setClientId(appSetting.getAppId());
                    accessTokenHolder.setClientSecret(appSetting.getSecret());
                    accessTokenHolder.setTokenUrl(url);
                } catch (Exception e) {
                    accessTokenHolder = new DefaultAccessTokenHolder(url, appSetting.getAppId(), appSetting.getSecret());
                }
            }
`
这个是留给有需要分布式部署的人扩展用的，你想使用默认的DefaultAccessTokenHolder 就不需要在配置里面设置tokenHolderClass。

不好意思让你心情不好了。

**Comment by howareyouo** [comment]
@borball 是不是应该把`AccessTokenHolder `里的几个私有属性改成`protected`的? 否则我想复用里面的逻辑又没办法拿到`clientId`和`httpClient`???

**Comment by borball** [comment]
Reopen it. 
@howareyouo 能解释一下为什么需要client id 和 httpClient吗？fetchAccessToken 方法应该足够了，拿到AccessToken之后自己可以随意存储到任意地方比如数据库或者Redis。

**Comment by howareyouo** [comment]
@borball
假设我是第三方平台的开发商，我要代理商户公众号发起微信api调用，需要拿到clientId请求自己的授权服务哪access_token，而不是直接拿clientId和secret去直接调用微信.

**Comment by borball** [comment]
Check this https://github.com/borball/weixin-sdk/commit/8999f2667f4f997e6c1dfc17ea853f82b7dec04e

**Comment by howareyouo** [comment]
@borball 
OK, 这里有`getter`方法就可以了,
还有另一个问题, 关于`WxClientFactory`这个类:
![image](https://user-images.githubusercontent.com/1881595/59477991-4c679a80-8e8a-11e9-83d9-062840781d95.png)
默认的实现是把所以`WxClient`放入本地缓存 , 但我作为第三方平台, 会有很多商户授权给我, 所以不能无限制往内存放`WxClient`, 我这只通过这种方式改造了一下, 不知道有没有更好的方案?

**Comment by borball** [comment]
应该OK, 加了个limit做保护

**Comment by howareyouo** [comment]
@borball 
那速度发布新版本咯, 等不及了, 可以关issue了 😃😀😄😁
