### ISSUE TITLE
paymentNotification 验证返回签名失败

### ISSUE THREAD

**Issue by dannyxu2015** [borball/weixin-sdk#38]
参考一个返回的数据（生产环境的微信回调数据）：
`<xml><appid><![CDATA[wx8b33756ca20faafa]]></appid><attach><![CDATA[58ec7f141497af0a3d38]]></attach><bank_type><![CDATA[HRBB_DEBIT]]></bank_type><cash_fee><![CDATA[26842]]></cash_fee><coupon_count><![CDATA[1]]></coupon_count><coupon_fee>58</coupon_fee><coupon_fee_0><![CDATA[58]]></coupon_fee_0><coupon_id_0><![CDATA[2000000000276621044]]></coupon_id_0><fee_type><![CDATA[CNY]]></fee_type><is_subscribe><![CDATA[Y]]></is_subscribe><mch_id><![CDATA[1360993902]]></mch_id><nonce_str><![CDATA[CrB7044SHiP3DXgV]]></nonce_str><openid><![CDATA[opa33wOoUVMnrYOOIO2rUDYV2x8I]]></openid><out_trade_no><![CDATA[59341bac1497af61be6eb40e947479]]></out_trade_no><result_code><![CDATA[SUCCESS]]></result_code><return_code><![CDATA[SUCCESS]]></return_code><sign><![CDATA[035A6D26A2AE461F84C0750C2DD092A2]]></sign><time_end><![CDATA[20170604224238]]></time_end><total_fee>26900</total_fee><trade_type><![CDATA[JSAPI]]></trade_type><transaction_id><![CDATA[4001952001201706044309990415]]></transaction_id></xml>`
可以看到里面还有几个字段：coupon_fee_0,coupon_id_0等，这些似乎在weixin-pay中的paymentNotification.java没有定义。会导致回调时校验签名失败吧？
请参考微信的[官方文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_7)
![image](https://cloud.githubusercontent.com/assets/10399106/26770771/2911c784-49ec-11e7-8a00-1c8364c7b930.png)

**Comment by borball** [comment]
的确有这个问题，之前的难点在与代金券的数量是不固定的，PaymentNotification里面比较难处理，所以有些字段被忽略了。
不过现在可以参考RefundQuery里面对动态数据的处理，需要点时间。。

**Comment by wodenwang** [comment]
@borball 我刚修复了一个项目中出现的这种情况.最近微信在大力推广鼓励金,出现这种情况还是蛮高频的.
临时的解决方案是在paymentNotification里面增加coupon_fee_0,coupon_id_0的映射(例如0...3),虽然不太优雅但是能立即解决问题.因为目前微信鼓励金(coupon)不会出现同时超过三条的情况.

**Comment by wodenwang** [comment]
@borball 如果没有很好的方案,建议临时先这么解决,起码可以保障现有项目可以正常运转.

**Comment by borball** [comment]
fixed at https://github.com/borball/weixin-sdk/commit/d2b337b3e98b787a38229a94f99ea1bce83eaa71

**Comment by borball** [comment]
@wodenwang 试一下

**Comment by kkomge** [comment]
能不能把coupon_id_x这里的节点直接转换成map，让其在业务中自己去get节点

**Comment by borball** [comment]
已经是这样了，都在others里面。

**Comment by dannyxu2015** [comment]
嗯，应该是可以的 ~
