### ISSUE TITLE
Pois获取门店列表数据解析有问题

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#4]
调用接口时，返回的门店列表数据如下：
{"errcode":0,"errmsg":"ok","business_list":[{"base_info":{"sid":"","business_name":"XX店","branch_name":"","address":"XX有限公司","telephone":"15000000000","categories":["公司企业,公司企业"],"city":"广州市","province":"广东省","offset_type":1,"longitude":113.323753357,"latitude":23.1488742828,"photo_list":[{"photo_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/U7n8alr3A5nJF6NsUztibfibuRn9Ur2NjCibmlzxzkwrnM6LNSXdEomlB0zUxu4uBSBYKXwicsUiaT66OMrBTIP3wAg\/0?wx_fmt=png"}],"introduction":"高级公司","recommend":"免费下午茶","special":"免费下午茶","open_time":"10:20","avg_price":100,"poi_id":"460656411","available_state":2,"district":"天河区","update_status":0}}],"total_count":1}

最终转化成List<Businesses> 内的Businesses只有avgPrice,latitude,longitude,offsetType,updated几个属性被设值进行，其它属性值为null

**Comment by borball** [comment]
Fixed at https://github.com/borball/weixin-sdk/commit/a56c13dcebfefb2090b253e49b1a1d8baf394bea
