### ISSUE TITLE
感谢开源，请问下，在官方文档中将消息发送到客服，只需要在响应中返回一个transfer_customer_service

### ISSUE THREAD

**Issue by SkyMoreStars** [borball/weixin-sdk#47]
在你的SDK中XmlMessageHeader设置了属性，
XmlMessageHeader xmlMessageHeader=new XmlMessageHeader();
        xmlMessageHeader.setMsgType(MsgType.transfer_customer_service);
        xmlMessageHeader.setCreateTime(new Date());
        xmlMessageHeader.setToUser(xmlRequest.getToUser());
        xmlMessageHeader.setFromUser("348699531");
通过response返回了。可是公众号提示异常，请问下该怎么处理这个问题。

**Comment by SkyMoreStars** [comment]
@borball

**Comment by kkomge** [comment]
XmlMessageHeader 是一个父类抽象，你如果响应消息，需要根据返回具体的消息类型来创建XmlMessageHeader 的下面的子类，如ImageXmlMessage，MusicXmlMessage，NewsXmlMessage，TextXmlMessage，VideoXmlMessage，VoiceXmlMessage。 @SkyMoreStars
