### ISSUE TITLE
注意-红包金额大于200时，请求参数scene_id必传

### ISSUE THREAD

**Issue by max-lim** [borball/weixin-sdk#54]
https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_4&index=3

以上是微信红包的官方文档，其中对scene_id参数有所要求，但是实现里面，没此参数
com.riversoft.weixin.pay.redpack.bean.RedPackRequest

**Comment by borball** [comment]
建议您在程序端自己处理，SDK端太细致的话会有很大工作量，特别是考虑到微信测经常 变动。
