### ISSUE TITLE
能否支持下微信文档上的数据统计接口

### ISSUE THREAD

**Issue by yuweichen** [borball/weixin-sdk#59]
我看好久 都没更新了样
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141084

**Comment by borball** [comment]
太复杂了，感觉全是体力活啊，要不要发个pull request？

**Comment by yuweichen** [comment]
我前段时间需要这个东西  不过最近因为一些事给耽搁了 
要是作者你没啥时间的话 我这边自己可以弄 要是我感觉自己写的比较完整的话就发给你看看 你可以修改合并下
