### ISSUE TITLE
小程序支付统一下单参数有问题

### ISSUE THREAD

**Issue by earlBell** [borball/weixin-sdk#60]
小程序支付统一下单接口，缺少很多请求参数、如随机字符串和签名等，这些参数都必需的。
小程序支付接口地址
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_1&index=1

**Comment by kkomge** [comment]
在BaseSettings里面吧，属于继承属性

**Comment by earlBell** [comment]
原来这样，我以为是我自己做签名，想不到都封装好了。感谢
