### ISSUE TITLE
门店模型 List<Photo>中，Photo模型内的url未做映射

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#7]
实际返回json值部分"photo_list":[{"photo_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/U7n8alr3A5nJF6NsUztibfibuRn9Ur2NjCibmlzxzkwrnM6LNSXdEomlB0zUxu4uBSBYKXwicsUiaT66OMrBTIP3wAg\/0?wx_fmt=png"}]

Photo模型内url未做photo_url的对应关系

**Comment by borball** [comment]
fixed at https://github.com/borball/weixin-sdk/commit/1b8da7afc6fc4787cdeae9efb55580f878623a96
