### ISSUE TITLE
公众号消息加解密

### ISSUE THREAD

**Issue by yyhSuper** [borball/weixin-sdk#75]
![image](https://user-images.githubusercontent.com/9104878/47084717-f6811b00-d246-11e8-89a5-cb0186cbf243.png)

![image](https://user-images.githubusercontent.com/9104878/47084782-321be500-d247-11e8-846d-adc708cf9afc.png)

echoStr 不参与加密计算，否则计算出来的值和原值不匹配

**Comment by yyhSuper** [comment]
![image](https://user-images.githubusercontent.com/9104878/47084815-4e1f8680-d247-11e8-8d98-98669f841e1c.png)
如果是url验证调用这个方法，直接return echoStr就可以了，不要再调用decrypt方法了

**Comment by borball** [comment]
@yyhSuper  最近没关注微信SDK了，这个是最近的改动吗?

**Comment by yyhSuper** [comment]
我是最近才用你的这个SDK ，和公众号进行联调的时候出现了这个问题，后面排查了一下是这边加密方法的问题，本来是想重写这个方法，一看里面很多都是私有的方法。完全没有办法扩展了

**Comment by borball** [comment]
@yyhSuper 没见SDK有更新，请参考demo里面的做法： com.riversoft.weixin.demo.mp.WxCallbackController。
