### ISSUE TITLE
地址配置文件中不存在url.material.mpnews.get及对应的接口地址

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#8]
Materials类下
public MpNews getMpNews(String mediaId) {
        String url = WxEndpoint.get("url.material.mpnews.get");

        String json = String.format("{\"media_id\":\"%s\"}", mediaId);
        logger.info("get mpnews: {}", json);
        String response = wxClient.post(url, json);
        return JsonMapper.defaultMapper().fromJson(response, MpNews.class);
    }

没有找到url.material.mpnews.get，报空指针异常

**Comment by borball** [comment]
fixed at https://github.com/borball/weixin-sdk/commit/1b8da7afc6fc4787cdeae9efb55580f878623a96
