### ISSUE TITLE
微信公众号模板消息回调xml转Obj异常

### ISSUE THREAD

**Issue by shiwenlin** [borball/weixin-sdk#84]
微信那边返回的msgId 是一串字符串的数字，但是代码中是以int去接收，导致转化失败报错

![image](https://user-images.githubusercontent.com/26130156/62341422-dbea0b00-b515-11e9-85f3-d1d315faf7dd.png)

![image](https://user-images.githubusercontent.com/26130156/62341329-7c8bfb00-b515-11e9-8b68-ffa915501057.png)

**Comment by borball** [comment]
升级一下版本，这个问题（issue #63 ）应该早就修过了。
