### ISSUE TITLE
希望去掉jackson1.x版本的依赖

### ISSUE THREAD

**Issue by CodinngLee** [borball/weixin-sdk#9]
项目中有@JsonProperty，却依赖了jackson1.x版本的annotate，导致项目下却要引入两个版本的jackson 项目包(1.x，2.x)，实际jackson2.x版中com.fasterxml.jackson.annotation同样提供了@JsonProperty，希望去掉1.x依赖，减小体积。

**Comment by borball** [comment]
Thanks for the suggestion, I didn't notice there was a 1.9.x dependecy; It is fixed at https://github.com/borball/weixin-sdk/commit/16b6b10c82a93f0427398c02d5e8cb446576400c.
